oerweekapi/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from django.urls import path

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

# TODO: not sure about this one
# from search import views as search_views

from web import views

from django.views.generic.base import RedirectView

from rest_framework import routers
import rest_framework_jwt.views

from web.views import (
    PageViewSet,
    ResourceViewSet,
    EventViewSet,
    EventSummaryView,
    ExportResources,
    ResourceImageViewSet,
    SubmissionViewSet,
    TwitterSearchResults,
    EmailTemplateView,
    RequestAccessView,
)

router = routers.DefaultRouter(trailing_slash=False)
router.register(r"pages", PageViewSet, basename="Page")
router.register(r"resource", ResourceViewSet, basename="Resource")
router.register(r"resource-image", ResourceImageViewSet, basename="ResourceImage")
router.register(r"event", EventViewSet, basename="Event")
router.register(r"submission", SubmissionViewSet, basename="Submission")
router.register(r"email-templates", EmailTemplateView)

urlpatterns = (
    [
        url(r"^api/", include(router.urls)),
        url(r"^api/events-summary/", EventSummaryView.as_view()),
        url(r"^api/twitter/", TwitterSearchResults.as_view()),
        url(r"^api/request-access/", RequestAccessView.as_view()),
        url(r"^admin/", admin.site.urls),
        url(r"^api-auth/", include("rest_framework.urls", namespace="rest_framework")),
        url(r"^api-token-auth/", rest_framework_jwt.views.obtain_jwt_token),
        url(r"^api-token-refresh/", rest_framework_jwt.views.refresh_jwt_token),
        url(r"^export/resources/$", ExportResources.as_view(), name="resource_export"),
        url(r"^$", views.index, name="web_index"),
        url(r"^submit$", RedirectView.as_view(url="/contribute/", permanent=False)),
        url(r"^submit/$", RedirectView.as_view(url="/contribute/", permanent=False)),
        url(
            r"^submit-activity$",
            RedirectView.as_view(url="/contribute-activity/", permanent=False),
        ),
        url(
            r"^submit-activity/$",
            RedirectView.as_view(url="/contribute-activity/", permanent=False),
        ),
        url(
            r"^submit-asset$",
            RedirectView.as_view(url="/contribute-asset/", permanent=False),
        ),
        url(
            r"^submit-asset/$",
            RedirectView.as_view(url="/contribute-asset/", permanent=False),
        ),
        url(r"^contribute$", RedirectView.as_view(url="/contribute/", permanent=False)),
        url(
            r"^contribute-activity$",
            RedirectView.as_view(url="/contribute-activity/", permanent=False),
        ),
        url(
            r"^contribute-asset$",
            RedirectView.as_view(url="/contribute-asset/", permanent=False),
        ),
        url(r"^contribute/$", views.contribute),
        url(r"^contribute-activity/$", views.contribute_activity),
        path(
            "contribute-activity/<uuid:identifier>/",
            views.contribute_activity,
            name="contribute-activity",
        ),
        url(r"^contribute-asset/$", views.contribute_asset),
        path(
            "contribute-asset/<uuid:identifier>/",
            views.contribute_asset,
            name="contribute-asset",
        ),
        path("edit/<uuid:identifier>/", views.edit_resource),
        url(r"^thanks/$", views.thanks),

        url(r"^calendar$", RedirectView.as_view(url="/schedule/all/", permanent=False)),
        url(r"^calendar/$", RedirectView.as_view(url="/schedule/all/", permanent=False)),
        url(r"^schedule$", RedirectView.as_view(url="/schedule/", permanent=True)),
        url(r"^schedule/$", RedirectView.as_view(url="/schedule/all/")),
        path(
            "schedule/custom/<str:events>/",
            views.custom_schedule_list,
            name="custom_schedule_list",
        ),
        path(
            "schedule/my/",
            views.my_schedule_list,
            name="my_schedule_list",
        ),
        path(
            "schedule/<str:day>/",
            views.schedule_list,
            name="schedule_list",
        ),
        path(
            "schedule/toggle-favorite/<int:year>/<str:slug>/",
            views.toggle_favorite_event,
            name="toggle_favorite_event",
        ),
        url(r"^library$", RedirectView.as_view(url="/", permanent=True)),
        url(r"^library/$", RedirectView.as_view(url="/", permanent=True)),
        url(
            r"^library/events$",
            RedirectView.as_view(url="/library/events/", permanent=True),
        ),
        url(r"^library/events/$", views.show_events_library, name="library_events"),
        url(
            r"^library/resources$",
            RedirectView.as_view(url="/library/resources/", permanent=True),
        ),
        url(
            r"^library/resources/$",
            views.show_resources_library,
            name="library_resources",
        ),
        url(r"^events$", RedirectView.as_view(url="/events/", permanent=True)),
        url(r"^events/$", views.show_events),
        url(r"^resources$", RedirectView.as_view(url="/resources/", permanent=True)),
        url(r"^resources/$", views.show_resources),
        path("events/<str:slug>/", views.handle_old_event_detail),
        path(
            "events/<int:year>/<str:slug>/",
            views.show_event_detail,
            name="show_event_detail",
        ),
        path("resources/<str:slug>/", views.handle_old_resource_detail),
        path(
            "resources/<int:year>/<str:slug>/",
            views.show_resource_detail,
            name="show_resource_detail",
        ),
        path("staff/", views.staff_view, name="staff_view"),
        path(
            "staff/approve/<int:id>/",
            views.approve_action,
            name="staff_approve_action",
        ),
        path(
            "staff/submit_feedback/",
            views.submit_resource_feedback,
            name="staff_submit_feedback",
        ),
        path("cms/", include(wagtailadmin_urls)),
        path("documents/", include(wagtaildocs_urls)),
        # redirect from legacy URL path to new URLs
        url(r"^about$", RedirectView.as_view(url="/pages/about/", permanent=True)),
        url(r"^about/$", RedirectView.as_view(url="/pages/about/", permanent=True)),
        url(r"^promote$", RedirectView.as_view(url="/pages/promote/", permanent=True)),
        url(r"^promote/$", RedirectView.as_view(url="/pages/promote/", permanent=True)),
        url(r"^about/faq$", RedirectView.as_view(url="/pages/faq/", permanent=True)),
        url(r"^about/faq/$", RedirectView.as_view(url="/pages/faq/", permanent=True)),
        url(r"^about/2023$", RedirectView.as_view(url="/pages/2023/", permanent=True)),
        url(r"^about/2023/$", RedirectView.as_view(url="/pages/2023/", permanent=True)),
        # redirect from semi-hardcoded "about" page to the newer about page
        url(
            r"^pages$", RedirectView.as_view(url="/pages/about/", permanent=False)
        ),  # not permanent
        url(
            r"^pages/$", RedirectView.as_view(url="/pages/about/", permanent=False)
        ),  # not permanent
        # wagtail URLs
        path("pages/", include(wagtail_urls)),
        # path("search/", search_views.search, name="search"),
        url(r"^set-timezone/$", views.set_timezone, name="set_timezone"),
        url(
            r"^set-timezone-reload/$",
            views.set_timezone_and_reload,
            name="set_timezone_reload",
        ),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

if settings.SIGNUP_ENABLED:
    urlpatterns += [
        path("auth/", include("magiclink.urls", namespace="magiclink")),
        path("profile/", include("contributor_profile.urls", namespace="c_profile")),
    ]

web/forms.py
from django import forms
from django.forms import ModelForm
from .models import Resource
from .data import COUNTRY_CHOICES


class ActivityForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['firstname'].widget.attrs.update({'class': 'mycustomclass'})

    class Meta:
        model = Resource
        fields = [
            # 'uuid',
            "post_type",  # event vs. resource
            "firstname",
            "lastname",
            "email",
            "twitter_personal",
            "twitter_institution",
            "institution",
            "institution_url",
            "institution_is_oeg_member",
            "country",
            "city",
            # 'event_type', # OPTIONS: local / online / anytime (asynchronous)
            "title",
            "event_facilitator",
            "content",  # 'DESCRIPTION',
            "event_time",  # event_source_datetime
            "link",
            "linkwebroom",
            "form_language",  # 'language',
            # 'opentags',
            # 'image',
            "user_image",
            "event_source_timezone",
            "newsletter",
        ]

    # uuid = forms.UUIDField(
    #     required = True,
    #     widget = forms.HiddenInput,
    # )

    post_type = forms.CharField(
        required=True,
        initial="event",
        widget=forms.HiddenInput,
    )

    firstname = forms.CharField(
        required=True,
        label="First Name (*)",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    lastname = forms.CharField(
        required=True,
        label="Last Name (*)",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    email = forms.CharField(
        required=True,
        label="Email (*)",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    twitter_personal = forms.CharField(
        required=False,
        label="Personal Twitter",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    twitter_institution = forms.CharField(
        required=False,
        label="Organizational Twitter",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    institution = forms.CharField(
        required=True,
        label="Name of Institution, Organization, Initiative (*)",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    institution_url = forms.CharField(
        required=True,
        label="Website of Institution, Organization, Initiative (*)",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    institution_is_oeg_member = forms.TypedChoiceField(
        label="Is the organization an OEGlobal member?",
        coerce=lambda x: x == "True",
        choices=((None, "Please select an option"), (False, "No"), (True, "Yes")),
    )

    # print(COUNTRY_CHOICES)
    # country = forms.ChoiceField(
    #     required=True,
    #     widget=forms.Select(
    #         choices=COUNTRY_CHOICES,
    #     ),
    # )

    city = forms.CharField(
        required=True,
        label="City, State (*)",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    title = forms.CharField(
        required=True,
        label="Activity Title (*)",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    event_facilitator = forms.CharField(
        required=False,
        label="Activity Facilitator",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    content = forms.CharField(
        required=True,
        label="Description (*)",
        widget=forms.Textarea(attrs={"class": "w-full"}),
    )

    link = forms.CharField(
        required=True,
        label="Link to the activity (*)",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    linkwebroom = forms.CharField(
        required=False,
        label="Link to the webroom (if applicable)",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    # firstname = forms.CharField(
    #     widget = forms.PasswordInput(
    #         attrs = {'class': 'errorlist'}
    #     )
    # )

    # firstname = forms.ChoiceField(
    #     widget   = forms.RadioSelect(
    #         attrs={
    #             'class': 'custom-control-input'
    #         }
    #     ),
    #     choices = (
    #         ('Peter', 'Blah Blah'),
    #     )
    # )

    user_image = forms.ImageField(
        required=False,
        label="Image",
    )

    event_source_timezone = forms.CharField(
        required=False,
        label="Event time zone",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )


class AssetForm(ModelForm):
    class Meta:
        model = Resource
        fields = [
            # 'uuid',
            "post_type",  # event vs. resource
            "firstname",
            "lastname",
            "email",
            "twitter_personal",
            "twitter_institution",
            "institution",
            "institution_url",
            "institution_is_oeg_member",
            "country",
            "city",
            "title",
            "content",  # 'DESCRIPTION',
            "link",
            "license",
            "form_language",  # 'language',
            # 'opentags',
            # 'image',
            "user_image",
            "event_source_timezone",
            "newsletter",
        ]

    # uuid = forms.UUIDField(
    #     required = True,
    #     widget = forms.HiddenInput,
    # )

    post_type = forms.CharField(
        required=True,
        initial="resource",
        widget=forms.HiddenInput,
    )

    firstname = forms.CharField(
        required=True,
        label="First Name (*)",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    lastname = forms.CharField(
        required=True,
        label="Last Name (*)",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    email = forms.CharField(
        required=True,
        label="Email (*)",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    twitter_personal = forms.CharField(
        required=False,
        label="Personal Twitter",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    twitter_institution = forms.CharField(
        required=False,
        label="Organizational Twitter",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    institution = forms.CharField(
        required=True,
        label="Name of Institution, Organization, Initiative (*)",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    institution_url = forms.CharField(
        required=True,
        label="Website of Institution, Organization, Initiative (*)",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    institution_is_oeg_member = forms.TypedChoiceField(
        label="Is the organization an OEGlobal member?",
        coerce=lambda x: x == "True",
        choices=((None, "Please select an option"), (False, "No"), (True, "Yes")),
    )

    # print(COUNTRY_CHOICES)
    # country = forms.ChoiceField(
    #     required=True,
    #     widget=forms.Select(
    #         choices=COUNTRY_CHOICES,
    #     ),
    # )

    city = forms.CharField(
        required=True,
        label="City, State (*)",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    title = forms.CharField(
        required=True,
        label="Asset Title (*)",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    content = forms.CharField(
        required=True,
        label="Description of Asset (*)",
        widget=forms.Textarea(attrs={"class": "w-full"}),
    )

    link = forms.CharField(
        required=True,
        label="Link to the asset (*)",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    # License (license)

    # Primary language (form_language)

    user_image = forms.ImageField(
        required=False,
        label="Image",
    )

    event_source_timezone = forms.CharField(
        required=False,
        label="Event time zone",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )


class ResourceFeedbackForm(ModelForm):
    class Meta:
        model = Resource
        fields = [
            "resource_id",  # event vs. resource
            "subject",
            "body",
        ]

    subject = forms.CharField(
        required=False,
        label="Subject",
        widget=forms.TextInput(attrs={"class": "w-full"}),
    )

    body = forms.CharField(
        required=False,
        label="Body",
        widget=forms.Textarea(attrs={"class": "w-full"}),
    )

    resource_id = forms.CharField(
        required=True,
        widget=forms.HiddenInput(),
    )

web/templates/web/contribute-activity.html
{% extends 'base.html' %}

{# "Content:" -> "Description:" #}
{# "City:" -> "City, State:" #}
{# "Institution:" -> "Institution or Organization:" #}
{# "Institution url:" -> "Website of Institution or Organization:" #}
{# "Form language:" -> "Language:" #}
{# "Event time:" -> "Activity starts at:" #}
{# "Link:" -> "Link to the activity:" #}
{# "Linkwebroom:" -> "Link to the webroom (if applicable):" #}
{# "Language:" -> "Primary Language:" #}

{% block extra_head %}
  <script>
    window.onload = function () {
      var input = document.getElementById('id_event_source_timezone');
      input.value = Intl.DateTimeFormat().resolvedOptions().timeZone;
    }
  </script>
{% endblock extra_head %}

{% block content %}
{% load wysiwyg %}
{% wysiwyg_setup %}

{% load tz %}
{% get_current_timezone as current_timezone %}

<h1>{{ action_verb }} Activity</h1>
<div class="card bg-white p-8 md:p-16 rounded shadow-lg">
    <img src="https://conference.oeglobal.org/2021/wp-content/uploads/2022/02/submission-banner.png" class="w-full mb-8">
    <div class="prose lg:prose-lg mx-auto">


        <p>Are you hosting an open education-focused activity during Open Education Week 2023? Look no further! Enter all the details here, and we will make sure it is featured alongside other exciting #oeweek events around the world!</p>

        <p>If you need to know more information before <strong>Contributing an Activity</strong>, <a href="/contribute/">here’s all you need to know</a>.</p>

        <form action="{{ submit_url }}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {#{{ form.uuid }}#} {# FYI: hidden field #}
        {{ form.post_type }} {# FYI: hidden field #}

        {% if form.errors %}
            <div class="alert alert-error">
                <p style="background-color: red; color: white;"><strong>This form contains errors. Please scroll down to fix them and submit again.</strong></p>
                <ul>
                    {% for field in form %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </ul>
                {% if form.non_field_errors %}
                    {{ form.non_field_errors }}
                {% endif %}
            </div>
        {% endif %}

        <hr class="my-8">

        <div></div>

        <p>
            {{ form.title.label_tag }}
            {{ form.title.errors }}
            {{ form.title }}
        </p>

        <p>
            {{ form.event_facilitator.label_tag }}
            {{ form.event_facilitator.errors }}
            {{ form.event_facilitator }}
        </p>

        <p>
            {{ form.content.label_tag }}
            {{ form.content.errors }}

            <br>Describe briefly the highlights of your activity/event. What will be the main focus of the session? Who would be most interested in participating? What are the expected outcomes? Include anything else you want to share.
            <br><em>Suggested length: 50-500 words. (Feel free to also provide thedescription in your own lanquage).</em>

            {{ form.content }}
            {% wysiwyg_editor "id_content" "id_content_editor" "{ toolbar: 'Custom', toolbar_Custom: [['Bold', 'Italic', 'Underline'], ['NumberedList', 'BulletedList'], ['Link', 'Unlink'], ['RemoveFormat', 'Source']]}" %}
        </p>

        <p>
            {{ form.user_image.label_tag }}
            {{ form.user_image.errors }}
            <br>Share an image that is representative of your activity - logo, symbol, icon, graphics, team photo, etc. If no image is provided a screenshot of your website will be uploaded.
            <br><em>Recommended size: 584x232 pixels</em>
            {{ form.user_image }}
        </p>

        <p>
            <label for="id_event_source_timezone">Your local time zone:</label>
            <br>We try to automatically detect your time zone. If it is wrong, select the correct value:
            <select name="event_source_timezone" id="id_event_source_timezone" class="w-full">
            {% for tz in timezones %}
                <option value="{{ tz }}"{% if tz == current_timezone %} selected{% endif %}>{{ tz }}</option>
            {% endfor %}
            </select>
        </p>

        <p>
            <label for="id_event_time">Activity starts at:</label>
            <br>Choose the time <strong>in your local time zone</strong>.
            <br>
            {{ form.event_time.errors }}
            <input type="datetime-local" name="event_time" id="id_event_time" value="{{ form.event_time.value|date:'Y-m-d H:i' }}"/>
        </p>

        {{ form.primarylanguage.errors }}
        {{ form.opentags.errors }}
        <div class="flex-none md:flex justify-between">
            <p class="w-full mr-2">
            <label for="id_form_language">Primary language:</label>
            <select name="form_language" id="id_form_language" class="w-full">
            {% for id, name in form.fields.form_language.choices %}
                <option value="{{ id }}"
                    {% if id == None %}disabled=""{% endif %}
                    {% if id == form.form_language.value %}selected=""{% endif %}
                >{{ name }}</option>
            {% endfor %}
            </select>
            </p>

            <!--
            <p class="w-full ml-2">
            <label for="id_opentags">Opentags:</label>
            <input type="text" name="opentags" maxlength="255" id="id_opentags" class="w-full" value="{{ form.opentags.value }}">
            </p>
            -->
        </div>

        {{ form.country.errors }}
        {{ form.city.errors }}
        <div class="flex-none md:flex justify-between">
            <p class="w-full mr-2">
            {{ form.country.label_tag }}
            <select name="country" id="id_country" class="w-full">
            {% for id, name in form.fields.country.choices %}
                <option value="{{ id }}"
                    {% if id == None %} disabled=""{% endif %}
                    {% if id == form.country.value %} selected=""{% endif %}
                >{{ name }}</option>
            {% endfor %}
            </select>
            </p>

            <p class="w-full ml-2">
                {{ form.city.label_tag }}
                {{ form.city }}
            </p>

        </div>

        <p>
            {{ form.link.label_tag }}
            {{ form.link.errors }}
            {{ form.link }}
        </p>

        <p>
            {{ form.linkwebroom.label_tag }}
            {{ form.linkwebroom.errors }}
            {{ form.linkwebroom }}
        </p>

        <hr class="my-8">

        <h2>Organization</h2>

        <div></div>

        <p>
            {{ form.institution.label_tag }}
            {{ form.institution.errors }}
            {{ form.institution }}
            <br>If this is an individual contribution not affiliated with an institution or organization you may fill in "Open Educator".
        </p>

        <p>
            {{ form.institution_url.label_tag }}
            {{ form.institution_url.errors }}
            {{ form.institution_url }}
        </p>

        <p>
            {{ form.twitter_institution.label_tag }}
            {{ form.twitter_institution.errors }}
            {{ form.twitter_institution }}
        </p>

        <p>
            {{ form.institution_is_oeg_member.label_tag }}
            {{ form.institution_is_oeg_member.errors }}
            &nbsp;
            {{ form.institution_is_oeg_member }}
        </p>

        <hr class="my-8">

        <h2>Contact person</h2>

        {{ form.firstname.errors }}
        {{ form.lastname.errors }}
        <div class="flex-none md:flex justify-between">
            <p class="w-full mr-2">
                {#<label for="id_firstname">First Name:</label>#}
                {#<input type="text" name="firstname" maxlength="255" id="id_firstname" class="w-full" value="{{ form.firstname.value }}">#}
                {{ form.firstname.label_tag }}
                {{ form.firstname }}
            </p>

            <p class="w-full ml-2">
                {{ form.lastname.label_tag }}
                {{ form.lastname }}
                {#<label for="id_lastname">Last Name:</label>#}
                {#<input type="text" name="lastname" maxlength="255" id="id_lastname" class="w-full" value="{{ form.lastname.value }}">#}
            </p>
        </div>

        {{ form.email.errors }}
        {{ form.twitter_personal.errors }}
        <div class="flex-none md:flex justify-between">
            <p class="w-full mr-2">
                {{ form.email.label_tag }}
                {{ form.email }}
            </p>
            <p class="w-full ml-2">
                {{ form.twitter_personal.label_tag }}
                {{ form.twitter_personal }}
            </p>
        </div>

        <p>
            {{ form.newsletter.label_tag }} <br>
            {{ form.newsletter.errors }}
            {{ form.newsletter }}
            Join the OEGlobal newsletter for updates
        </p>

        <input type="submit" value="Submit" class="button-outline font-bold my-8">
        </form>

        {% if contribute_similar %}
        <hr class="my-8">
        <p>You can submit similar entry by <a href="{{ contribute_similar }}">clicking here</a>.</p>
        {% endif %}
        </div><!-- prose -->
 </div> <!-- card -->
{% endblock %}

web/templates/web/resource-feedback-sent.html
{% extends 'base.html' %}

{% block content %}

<h1>Done!</h1>
<div class="prose">
    <p>Thank you! Contribution processed.</p>

    <p><a href="{% url 'staff_view' %}">&#8592;Back to approval list</a></p>
</div>
{% endblock %}

web/templates/web/send-resource-feedback.html
{% extends 'base.html' %}


{% block content %}

<h1>Send feedback</h1>
<div class="card bg-white p-8 lg:p-16 rounded shadow-lg prose">
    <h2>{{ resource.title }}</h2>
    <p>Contribution status was set to '{{ resource.post_status }}'.</p>
    <p>Now you can send the message to the contributor. If you not wish to send a message, then clear the body or simply leave
    (for example back to <a href="{% url 'staff_view' %}">approval list</a>).</p>

    <form action="{% url 'staff_submit_feedback' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {% if form.errors %}
        <div class="alert alert-error">
            <p style="background-color: red; color: white;"><strong>This form contains errors. Please scroll down to fix them and submit again.</strong></p>
            <ul>
                {% for field in form %}
                    {% if field.errors %}
                        {% for error in field.errors %}
                            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
                        {% endfor %}
                    {% endif %}
                {% endfor %}
            </ul>
            {% if form.non_field_errors %}
                {{ form.non_field_errors }}
            {% endif %}
        </div>
    {% endif %}

    <hr class="my-8">
    <br>

    <p>
        {{ form.subject.label_tag }}
        {{ form.subject.errors }}
        {{ form.subject }}
    </p>

    <p>
        {{ form.body.label_tag }}
        {{ form.body.errors }}
        {{ form.body }}
    </p>

    {{ form.resource_id }}
    <input type="submit" value="Submit" class="button-outline font-bold my-8">
    </form>

    <p class="my-6"><a href="{% url 'staff_view' %}">&#8592;Back to approval list</a></p>
</div>
{% endblock %}

web/templates/web/snippet-days_to_go.html
{% if days_to_go %}
    <div class="days-to-go">
        <div class="inner-days shadow-lg text-purple-800 z-20 px-8 py-2 bg-white z-20 rounded-full italic text-sm md:text-2x"><i class="fas fa-alarm-clock mr-4"></i>{{days_to_go}} days until Open Education Week {{days_to_go_year}}!</div>
    </div>
{% endif %}

web/templates/web/thanks.html
{% extends 'base.html' %}

{% block content %}

<h1>Thank you!</h1>
<div class="prose lg:prose-lg">
    <p>Thank you for contributing "{{ title }}" for Open Education Week. You will be notified by email about the status of your contribution, and once accepted, it will be added to the OE Week website.</p>

    <h2>You may now:</h2>

    <ul class="list-none pl-0! ml-0!">
      <li><a href="/edit/{{ uuid }}/"><i class="fa-light fa-pen-to-square"></i> Review/edit</a> your entry</li>
      <li><a href="{{ contribute_similar }}"><i class="fa-light fa-paper-plane"></i> Submit a new entry</a> (with same contact information)</li>
      <li><a href="/"><i class="fa-light fa-arrow-rotate-left"></i> Return to Open Education Week</a></li>
    </ul>
</div>
{% endblock %}

web/templates/web/timezone.html
{{ result }}

web/templates/web/toggle-favorite.html
{% if favorited == True %}
<i class="fa-solid fa-bookmark text-green-500"></i>
{% elif favorited == False %}
<i class="fa-regular fa-bookmark text-gray-400"></i>
{% else %}
<i class="fa-thin fa-bookmark text-gray-200"></i>
{% endif %}

web/templates/web/updated.html
{% extends 'base.html' %}

{% block content %}

<h1>You rock!</h1>
<div class="prose">
    <p>Thank you! Your contribution has been updated and saved successfully.</p>

    <p><a href="/pages/">Why not tell others about it?</a></p>
</div>
{% endblock %}